const catalogoPatrones = [
  { 'codigo':'00001','nombre':'AbrazaCortinasCochino-es','descripcion':'abrazacortinas cochino','etiquetas':'abrazacortinas cochino,abrazacortinas,cochino','idLink':'214822'},
  { 'codigo':'00002','nombre':'AbrazaCortinasConejo-es','descripcion':'abrazacortinas conejo','etiquetas':'abrazacortinas conejo,abrazacortinas,conejo','idLink':'214823'},
  { 'codigo':'00003','nombre':'AbrazaCortinasDinosaurio-es','descripcion':'abrazacortinas dinosaurio','etiquetas':'abrazacortinas dinosaurio,abrazacortinas,dinosaurio,dino','idLink':'214824'},
  { 'codigo':'00004','nombre':'AbrazaCortinasFridaKalho-es','descripcion':'abrazacortinas frida kalho','etiquetas':'abrazacortinas frida kalho,abrazacortinas,frida kalho,frida,kalho','idLink':'214825'},
  { 'codigo':'00005','nombre':'AbrazaCortinasMono-es','descripcion':'abrazacortinas mono','etiquetas':'abrazacortinas mono,abrazacortinas,mono,chango','idLink':'214826'},
  { 'codigo':'00006','nombre':'AbrazaCortinasTigre-es','descripcion':'abrazacortinas tigre','etiquetas':'abrazacortinas tigre,abrazacortinas,tigre','idLink':'214827'},
  { 'codigo':'00007','nombre':'AguacatesEnamorados-es','descripcion':'aguacates enamorados','etiquetas':'aguacates enamorados,aguacates,enamorados','idLink':'214829'},
  { 'codigo':'00008','nombre':'Ajolotes-es','descripcion':'ajolotes','etiquetas':'ajolotes,ajolote','idLink':'214833'},
  { 'codigo':'00009','nombre':'AlfileteroTotoro-es','descripcion':'alfiletero totoro','etiquetas':'alfiletero totoro','idLink':'214831'},
  { 'codigo':'00010','nombre':'Amiguruminis-es','descripcion':'amiguruminis','etiquetas':'amiguruminis miniatura,amiguruminis,miniatura','idLink':'214995'},
  { 'codigo':'00011','nombre':'AngelCerditaPippa-es','descripcion':'angel cerdita pippa','etiquetas':'angel cerdita pippa,angel,cerdita, pippa,cerdo,cochino,chancho','idLink':'214867'},
  { 'codigo':'00012','nombre':'Angelitos-es','descripcion':'angelitos','etiquetas':'angelitos,angel,angelito','idLink':'214835'},
  { 'codigo':'00013','nombre':'AngelOsoTeddy-es','descripcion':'angel oso teddy','etiquetas':'angel oso teddy,angel,oso,teddy','idLink':'214836'},
  { 'codigo':'00014','nombre':'Animatronicos4FNAF-es','descripcion':'animatronicos 4FNAF','etiquetas':'animatronicos 4FNAF,animatronicos,4FNAF','idLink':'214837'},
  { 'codigo':'00015','nombre':'BabyBaphyDemon-es','descripcion':'baby baphy demon','etiquetas':'baby baphy demon,baby,baphy,demon','idLink':'214838'},
  { 'codigo':'00016','nombre':'BabyDisney6-es','descripcion':'baby disney 6 personajes','etiquetas':'baby disney 6 personajes,caricatura,baby,disney,6,personaje','idLink':'214842'},
  { 'codigo':'00017','nombre':'BabyYodaCorazonMini-es','descripcion':'Baby Yoda con corazon mini','etiquetas':'baby yoda con corazon,baby,yoda con corazon,yoda,corazon,mini,película,pelicula,personaje','idLink':'214840'},
  { 'codigo':'00018','nombre':'BabyYoda-es','descripcion':'baby Yoda','etiquetas':'baby yoda película,baby,yoda,película,pelicula,hecho,personaje','idLink':'214839'},
  { 'codigo':'00019','nombre':'BaphometDemon-es','descripcion':'baphomet demon','etiquetas':'baphomet demon,baphomet,demon','idLink':'214841'},
  { 'codigo':'00020','nombre':'BaseConejoMila32cm-es','descripcion':'base conejo mila 32cm','etiquetas':'base conejo mila 32cm,base,conejo,mila,32cm','idLink':'214878'},
  { 'codigo':'00021','nombre':'BebeConChupon-es','descripcion':'bebé con chupón','etiquetas':'bebé con chupón ,bebé,chupón,bebe,baby,chupon,doll,muñeca','idLink':'215174'},
  { 'codigo':'00022','nombre':'BebeDisfrazJirafa-es','descripcion':'bebé con disfraz de jirafa','etiquetas':'bebé con disfraz de jirafa,bebé,bebe,baby,disfraz,outfit,jirafa,doll,muñeca','idLink':'214843'},
  { 'codigo':'00023','nombre':'BebeDragon-es','descripcion':'bebé dragón','etiquetas':'bebé dragón baby,bebé,bebe,baby,dragón,dragon','idLink':'214844'},
  { 'codigo':'00024','nombre':'BlancaNieves-es','descripcion':'blanca nieves','etiquetas':'blanca nieves,blanca,nieves,doll,muñeca,princesa,princesas,caricatura,personaje','idLink':'214846'},
  { 'codigo':'00025','nombre':'Bodoque-es','descripcion':'bodoque','etiquetas':'bodoque,personaje,hecho','idLink':'214847'},
  { 'codigo':'00026','nombre':'BolsoMono-es','descripcion':'bolso mono','etiquetas':'bolso mono,bolso,bolsa,bulto,mono,monito,chango','idLink':'214967'},
  { 'codigo':'00027','nombre':'BooMonsters-es','descripcion':'boo monsters inc','etiquetas':'boo monsters inc,boo,monsters inc,monsters,inc,outfit,caricatura,animado,personaje','idLink':'214849'},
  { 'codigo':'00028','nombre':'Brujita-es','descripcion':'brujita','etiquetas':'brujita,bruja,halloween','idLink':'214851'},
  { 'codigo':'00029','nombre':'Bts7-es','descripcion':'bts 7 personajes','etiquetas':'bts 7 personajes,bts,7,personajes,personaje','idLink':'214853'},
  { 'codigo':'00030','nombre':'BuhitaVestido-es','descripcion':'buhita con vestido','etiquetas':'buhita con vestido,búho,buho,buhita,vestido,outfit','idLink':'214854'},
  { 'codigo':'00031','nombre':'BuhoSujetaPuertas-es','descripcion':'búho sujetapuertas','etiquetas':'búho sujetapuertas,búho,buho,sujetapuertas','idLink':'214857'},
  { 'codigo':'00032','nombre':'BulldogPuppy16x14cm-es','descripcion':'bulldog puppy 16 x 14 cm','etiquetas':'bulldog puppy 16cm x 14 cm,bulldog,perro,puppy,16cm,14cm','idLink':'214855'},
  { 'codigo':'00033','nombre':'BulmaDragonBall-es','descripcion':'bulma dragon ball','etiquetas':'bulma dragon ball,bulma,dragon ball,personaje,doll,muñeca,caricatura,manga,anime','idLink':'214856'},
  { 'codigo':'00034','nombre':'BuzzLightyear-es','descripcion':'buzz lightyear','etiquetas':'buzz lightyear,buzz,lightyear,muñeco,caricatura,animado','idLink':'214859'},
  { 'codigo':'00035','nombre':'CabezasDeGato4-es','descripcion':'cabeza de gato','etiquetas':'cabeza de gato,4 cabezas de gato,4,cabezas,cabeza,gato','idLink':'214859'},
  { 'codigo':'00036','nombre':'Cactus2-es','descripcion':'2 tipos de cactus','etiquetas':'2 tipos de cactus,2,tipos de cactus,tipo,cactus','idLink':'214862'},
  { 'codigo':'00037','nombre':'Cactus3-es','descripcion':'3 tipos de cactus','etiquetas':'3 tipos de cactus,3,tipos de cactus,tipo,cactus','idLink':'214860'},
  { 'codigo':'00038','nombre':'Cactus9pequenos-es','descripcion':'9 tipos de cactus','etiquetas':'9 tipos de cactus,9, tipos de cactus, tipo, cactus','idLink':'214861'},
  { 'codigo':'00039','nombre':'CactusEnMacetaDeConejo-es','descripcion':'cactus en maceta de conejo','etiquetas':'cactus en maceta de conejo,cactus,maceta,maceta de conejo,conejo','idLink':'214863'},
  { 'codigo':'00040','nombre':'CandYMint-es','descripcion':'Candy y Mint','etiquetas':'candy y mint,candy,mint,doll,muñeca,plus,unicornio','idLink':'214868'},
  { 'codigo':'00041','nombre':'CaperucitaRoja-es','descripcion':'Caperucita Roja','etiquetas':'caperucita roja,caperucita,roja,doll,muñeca,libro,cuento,personaje','idLink':'214864'},
  { 'codigo':'00042','nombre':'CarlitosRugrats-es','descripcion':'Carlitos Rugrats 20cm','etiquetas':'carlitos rugrats 20cm,carlitos,rugrats,20cm,personaje,muñeco,caricatura,plus','idLink':'217011'},
  { 'codigo':'00043','nombre':'CarlYEllieUps-es','descripcion':'Carl y Ellie - Ups','etiquetas':'carl y ellie - ups,carl,ellie,ups,personaje,caricatura,animado','idLink':'214865'},
  { 'codigo':'00044','nombre':'Catherina-es','descripcion':'Catherina','etiquetas':'catherina,doll,muñeca','idLink':'214866'},
  { 'codigo':'00045','nombre':'CincoPatrones-es','descripcion':'5 Patrones kinder','etiquetas':'5 patrones kinder,5,patrones,kinder,ratón,raton,dinosaurio,dino,cocodrilo,payaso,crayolas,crayola','idLink':'214870'},
  { 'codigo':'00046','nombre':'CocodriloConrad-es','descripcion':'cocodrilo Conrad','etiquetas':'cocodrilo conrad con aro,cocodrilo,conrad,aro','idLink':'214880'},
  { 'codigo':'00047','nombre':'ComeGalletas-es','descripcion':'Comegalletas Plaza Sésamo','etiquetas':'comegalletas plaza sésamo, comegalletas plaza sesamo,comegalletas,plaza,sésamo,sesamo,personaje','idLink':'214871'},
  { 'codigo':'00048','nombre':'ConejaAlma-es','descripcion':'coneja Alma','etiquetas':'coneja alma,coneja,conejo,alma','idLink':'214872'},
  { 'codigo':'00049','nombre':'ConejaBonny-es','descripcion':'coneja Bonny','etiquetas':'coneja bonny,coneja,conejo,bonny','idLink':'214873'},
  { 'codigo':'00050','nombre':'ConejaEsther-es','descripcion':'coneja Esther','etiquetas':'coneja esther,coneja,conejo,esther','idLink':'214874'},
  { 'codigo':'00051','nombre':'ConejaMaggie-es','descripcion':'coneja Maggie','etiquetas':'coneja maggie,coneja,conejo,maggie','idLink':'214875'},
  { 'codigo':'00052','nombre':'ConejaRusa-es','descripcion':'coneja Rusa','etiquetas':'coneja rusa,coneja,conejo,rusa,ruso','idLink':'214877'},
  { 'codigo':'00053','nombre':'ConejaSophie-es','descripcion':'coneja Sophie','etiquetas':'coneja sophie,coneja,conejo,sophie','idLink':'214876'},
  { 'codigo':'00054','nombre':'ConejaVestidoAzul-es','descripcion':'coneja vestido azul','etiquetas':'coneja vestido azul,coneja,conejo,vestido,azul','idLink':'215177'},
  { 'codigo':'00055','nombre':'ConejitaAdriana-es','descripcion':'conejita Adriana','etiquetas':'conejita adriana,conejita,coneja,conejo,adriana','idLink':'217036'},
  { 'codigo':'00056','nombre':'ConejitaConVestido-es','descripcion':'conejita con vestido','etiquetas':'conejita con vestido,conejita,coneja,conejo,vestido','idLink':'217034'},
  { 'codigo':'00057','nombre':'ConejitaMia-es','descripcion':'conejita Mía','etiquetas':'conejita mía,conejita mia,conejita,coneja,conejo,mía,mia','idLink':'217035'},
  { 'codigo':'00058','nombre':'ConejoRaton33cm-es','descripcion':'conejo mameluco ratón 33 cm','etiquetas':'conejo mameluco ratón 33cm,conejo,mameluco,ratón,33cm','idLink':'217045'},
  { 'codigo':'00059','nombre':'Corazon-es','descripcion':'corazón','etiquetas':'corazón,corazon,mini','idLink':'214879'},
  { 'codigo':'00060','nombre':'CosmoPadrinosMagicos-es','descripcion':'Cosmo Padrinos Mágicos','etiquetas':'cosmo padrinos mágicos,cosmo padrinos magicos,cosmo,padrinos,mágicos,magicos,personaje,muñeco,caricaturas','idLink':'214881'},
  { 'codigo':'00061','nombre':'CostureroAbuela-es','descripcion':'costurero abuela','etiquetas':'costurero abuela,costurero,abuela,doll,muñeca','idLink':'214828'},
  { 'codigo':'00062','nombre':'CostureroGato-es','descripcion':'costurero gato','etiquetas':'costurero gato,costurero,gato','idLink':'214882'},
  { 'codigo':'00063','nombre':'CruellaDeVil-es','descripcion':'Cruella de Vil','etiquetas':'cruella de vil,cruella,vil,personaje,doll,muñeca,película','idLink':'214883'},
  { 'codigo':'00064','nombre':'CuPigdo-es','descripcion':'Cupigdo','etiquetas':'Cupigdo,cupido,cerdo,cochino,chancho','idLink':'214889'},
  { 'codigo':'00065','nombre':'DinoColorido-es','descripcion':'dinosaurio azul','etiquetas':'dinosaurio azul,dinosaurio,dino,azul,colorido,rayado','idLink':'217040'},
  { 'codigo':'00066','nombre':'DinoJoaco-es','descripcion':'Dino Joaco','etiquetas':'dino joaco,dino,joaco,dinosaurio','idLink':'217037'},
  { 'codigo':'00067','nombre':'DinoKnotjira-es','descripcion':'Dino Knotjira','etiquetas':'dino knotjira,dinosaurio,dino,knotjira,personaje,corto,animado','idLink':'217038'},
  { 'codigo':'00068','nombre':'DinoLucky-es','descripcion':'Dino Lucky','etiquetas':'dino lucky,dino,lucky,dinosaurio','idLink':'217039'},
  { 'codigo':'00069','nombre':'DiosHuitzilopochtli-es','descripcion':'Dios Huitzilopochtli','etiquetas':'dios huitzilopochtli,dios,huitzilopochtli,mexica,guerra','idLink':'214888'},
  { 'codigo':'00070','nombre':'DiosMictlantecuhtli-es','descripcion':'Dios Mictlantecuhtli','etiquetas':'dios mictlantecuhtli,dios,mictlantecuhtli,mexica,muerte','idLink':'214890'},
  { 'codigo':'00071','nombre':'DiosQuetzalcoatl-es','descripcion':'Dios Quetzalcoatl','etiquetas':'dios quetzalcoatl,dios,quetzalcoatl,azteca','idLink':'214891'},
  { 'codigo':'00072','nombre':'DiosTlaloc-es','descripcion':'Dios Tláloc','etiquetas':'dios tláloc,dios,tláloc,tlaloc,mexica,lluvia','idLink':'214892'},
  { 'codigo':'00073','nombre':'DollAliciaYConejo-es','descripcion':'Alicia y conejo','etiquetas':'alicia y conejo,alicia,conejo,doll,muñeca','idLink':'217029'},
  { 'codigo':'00074','nombre':'DollAnastasia-es','descripcion':'Anastasia','etiquetas':'anastasia,personaje,doll,muñeca,elfa,elfo','idLink':'214893'},
  { 'codigo':'00075','nombre':'DollAnne-es','descripcion':'Anne','etiquetas':'anne,doll,muñeca','idLink':'214895'},
  { 'codigo':'00076','nombre':'DollAutumn-es','descripcion':'Autumn','etiquetas':'autumn,doll,muñeca','idLink':'214987'},
  { 'codigo':'00077','nombre':'DollBailarinasElLago-es','descripcion':'Bailarinas - El Lago de las sombras','etiquetas':'bailarinas - el lago de las sombras, bailarinas, el lago de las sombras, lago,sombras,doll,muñeca','idLink':'214989'},
  { 'codigo':'00078','nombre':'DollCandyCandy-es','descripcion':'Candy Candy','etiquetas':'candy candy,candy,doll,muñeca,caricaturas,personaje','idLink':'217004'},
  { 'codigo':'00079','nombre':'DollConejo-es','descripcion':'Muñeca con conejo','etiquetas':'muñeca con conejo,muñeca,conejo,doll,plus','idLink':'214896'},
  { 'codigo':'00080','nombre':'DollDulce-es','descripcion':'Dulce navideña','etiquetas':'dulce navideña,navideña,muñeca,doll,navideño,navidad','idLink':'214897'},
  { 'codigo':'00081','nombre':'DollDulceNoa-es','descripcion':'Dulce Noa','etiquetas':'dulce noa,dulce,noa,doll,muñeca','idLink':'214898'},
  { 'codigo':'00082','nombre':'DollElenaDeAvalor-es','descripcion':'Elena de Avalor','etiquetas':'elena de avalor,elena,avalor,princesa,princesas,personaje,doll,muñeca','idLink':'214899'},
  { 'codigo':'00083','nombre':'DollEly-es','descripcion':'Ely','etiquetas':'ely,doll,muñeca','idLink':'217061'},
  { 'codigo':'00084','nombre':'DollEvaYOto-es','descripcion':'Eva y Oto','etiquetas':'eva y oto,eva,oto,doll,muñeca,oso,plus','idLink':'214906'},
  { 'codigo':'00085','nombre':'DollFiona-es','descripcion':'Fiona','etiquetas':'fiona,personaje,caricatura,animado','idLink':'214900'},
  { 'codigo':'00086','nombre':'DollFridaKahloBaby-es','descripcion':'Frida Kahlo baby','etiquetas':'frida kahlo baby,frida kahlo,frida,kahlo,baby,doll,muñeca,bebé,bebe','idLink':'214924'},
  { 'codigo':'00087','nombre':'DollFridaMini-es','descripcion':'Frida Kahlo mini','etiquetas':'frida kahlo mini,frida,kahlo,mini,doll,muñeca','idLink':'214901'},
  { 'codigo':'00088','nombre':'DollGraduada-es','descripcion':'Graduada','etiquetas':'graduada,doll,muñeca','idLink':'214972'},
  { 'codigo':'00089','nombre':'DollIcelyn-es','descripcion':'Icelyn','etiquetas':'Icelyn,doll,muñeca','idLink':'215154'},
  { 'codigo':'00090','nombre':'DollKiki-es','descripcion':'Kiki mini','etiquetas':'kiki mini,kiki,mini,doll,muñeca','idLink':'214902'},
  { 'codigo':'00091','nombre':'DollLalkaYChloe-es','descripcion':'Lalka y Chloe','etiquetas':'lalka y chloe,lalka,chloe,doll,muñeca','idLink':'214903'},
  { 'codigo':'00092','nombre':'DollLilly-es','descripcion':'Lilly','etiquetas':'Lilly,doll,muñeca,plus','idLink':'214904'},
  { 'codigo':'00093','nombre':'DollMariaFlorDePina-es','descripcion':'Maria Flor de Piña','etiquetas':'maria flor de Piña,doll,muñeca,colorido','idLink':'214960'},
  { 'codigo':'00094','nombre':'DollMariaJulia-es','descripcion':'Maria Julia','etiquetas':'maria julia,maria,julia,doll,muñeca','idLink':'214905'},
  { 'codigo':'00095','nombre':'DollMercedita6-es','descripcion':'Mercedita 6 diseños','etiquetas':'mercedita 6 diseños,merceditas,mercedita,6,diseños,doll,muñeca','idLink':'214908'},
  { 'codigo':'00096','nombre':'DollMoana-es','descripcion':'Moana','etiquetas':'moana,princesa,princesas,personaje,doll,muñeca,caricaturas,animado','idLink':'214993'},
  { 'codigo':'00097','nombre':'DollMolly-es','descripcion':'Molly','etiquetas':'molly,doll,muñeca','idLink':'214907'},
  { 'codigo':'00098','nombre':'DollNezuko-es','descripcion':'Nezuko Kimetsu','etiquetas':'nezuko kimetsu,nezuko,kimetsu,personaje,caricaturas,anime','idLink':'214977'},
  { 'codigo':'00099','nombre':'DollNina-es','descripcion':'Nina','etiquetas':'nina,doll,muñeca','idLink':'214909'},
  { 'codigo':'00100','nombre':'DollOhanaStich-es','descripcion':'Lilo y Stitch','etiquetas':'lilo y stitch,lilo,stitch,doll,muñeca,miniatura','idLink':'214834'},
  { 'codigo':'00101','nombre':'DollPayasita-es','descripcion':'Payasita','etiquetas':'payasita,payaso,doll,muñeca','idLink':'214966'},
  { 'codigo':'00102','nombre':'DollPrincesaRapunzel-es','descripcion':'Princesa Rapunzel','etiquetas':'princesa rapunzel,princesa,princesas,rapunzel,personaje,doll,muñeca','idLink':'215010'},
  { 'codigo':'00103','nombre':'DollRebeca-es','descripcion':'Rebeca','etiquetas':'rebeca,doll,muñeca','idLink':'214914'},
  { 'codigo':'00104','nombre':'DollRinLinInuyasha-es','descripcion':'Rin Lin Inuyasha','etiquetas':'rin lin inuyasha,rin,lin,inuyasha,personaje,doll, muñeca,caricatura,anime,manga','idLink':'214910'},
  { 'codigo':'00105','nombre':'DollSakura-es','descripcion':'Sakura Haruno','etiquetas':'sakura haruno,sakura,haruno,doll,muñeca,caricatura,anime,manga,plus','idLink':'214911'},
  { 'codigo':'00106','nombre':'DollThuyAnh-es','descripcion':'Thuy Anh Mérida','etiquetas':'thuy anh mérida,thuy anh,thuy,anh,mérida,merida,princesa,princesas,personaje,doll,muñeca','idLink':'214912'},
  { 'codigo':'00107','nombre':'DollTilda-es','descripcion':'Tilda','etiquetas':'tilda,doll,muñeca,bonito,plus','idLink':'214913'},
  { 'codigo':'00108','nombre':'DollTurca-es','descripcion':'Turca','etiquetas':'turca,doll,muñeca,bonito','idLink':'217053'},
  { 'codigo':'00109','nombre':'DollUnicornioLol-es','descripcion':'Unicornio Lol','etiquetas':'unicornio lol,unicornio,lol,doll,muñeca,coneja,conejo','idLink':'217048'},
  { 'codigo':'00110','nombre':'DollVioleta-es','descripcion':'Violeta la niña Pom Pom','etiquetas':'violeta la niña pom pom,violeta,la niña pom pom,pom pom,pom,doll,muñeca,plus','idLink':'214916'},
  { 'codigo':'00111','nombre':'DollZara-es','descripcion':'Zara','etiquetas':'zara,doll,muñeca','idLink':'214915'},
  { 'codigo':'00112','nombre':'DollZoey-es','descripcion':'Zoey','etiquetas':'zoey,doll,muñeca,bonito,plus','idLink':'214917'},
  { 'codigo':'00113','nombre':'DragonChimuelo-es','descripcion':'Chimuelo - Cómo entrenar a tu Dragón','etiquetas':'chimuelo - cómo entrenar a tu dragón,como entrenar a tu dragón,como entrenar a tu dragon,chimuelo,dragón,dragon,personaje,caricatura,animado','idLink':'217032'},
  { 'codigo':'00114','nombre':'DuendePachitoPlus-es','descripcion':'Duende Pachito','etiquetas':'duende pachito,duende,pachito,navideño,navidad,plus','idLink':'217043'},
  { 'codigo':'00115','nombre':'EdicionSanValentin10-es','descripcion':'Edición San Valentín','etiquetas':'edición san valentín, edicion san valentin, san valentin, san valentín, muñeco, oso, corazón, corazon, perro, ratón, raton, serpiente, monito, mono, chango, llavero,mini','idLink':'214923'},
  { 'codigo':'00116','nombre':'ElefanteGris-es','descripcion':'Elefante Gris','etiquetas':'elefante gris,elefante,gris,bonito,plus,hecho','idLink':'215172'},
  { 'codigo':'00117','nombre':'ElPrincipito-es','descripcion':'El Principito y Zorro','etiquetas':'el principito y zorro,el principito,zorro,muñeco,mini,libro,personaje','idLink':'214918'},
  { 'codigo':'00118','nombre':'ElPrincipitoPlus-es','descripcion':'El Principito','etiquetas':'el principito,libro,free,gratis,plus,personaje','idLink':'217044'},
  { 'codigo':'00119','nombre':'ElSombrereroLoco-es','descripcion':'El Sombrerero Loco','etiquetas':'el sombrerero loco,el sombrerero,sombrerero,muñeco,alicia,personaje','idLink':'214919'},
  { 'codigo':'00120','nombre':'FlashMamaGallina-es','descripcion':'Flash mini','etiquetas':'flash,mini,personaje','idLink':'214920'},
  { 'codigo':'00121','nombre':'FreddieMercury-es','descripcion':'FreddieMercury','etiquetas':'freddie mercury,freddie,mercury','idLink':'214921'},
  { 'codigo':'00122','nombre':'FreddieMercuryIWantToBreakFree-es','descripcion':'Freddie Mercury I Want To Break Free','etiquetas':'freddie mercury i want to break free,freddie mercury,freddie,mercury,muñeco,mini','idLink':'214922'},
  { 'codigo':'00123','nombre':'GataMia-es','descripcion':'Gata Mía con corazón','etiquetas':'gata mía con corazón,gata mia con corazon,gata,gato,mía,mia,corazon,corazón,mini','idLink':'214963'},
  { 'codigo':'00124','nombre':'GatoGrisRealistaGde-es','descripcion':'Gato gris realista','etiquetas':'gato gris realista,gato gris,gato,gris,realista','idLink':'214925'},
  { 'codigo':'00125','nombre':'GatoNavidad-es','descripcion':'Gato suéter rojo','etiquetas':'gato suéter rojo,gato,suéter,sueter,sweater,rojo','idLink':'217046'},
  { 'codigo':'00126','nombre':'Gerbera-es','descripcion':'Gerbera','etiquetas':'gerbera,gemma,flor,doll,muñeca,28cm','idLink':'214926'},
  { 'codigo':'00127','nombre':'Girasol-es','descripcion':'Girasol','etiquetas':'girasol,flor','idLink':'214928'},
  { 'codigo':'00128','nombre':'Girasoles-es','descripcion':'Girasoles','etiquetas':'girasoles,girasol,flor','idLink':'214929'},
  { 'codigo':'00129','nombre':'Goku-es','descripcion':'Goku - Dragon ball Z','etiquetas':'goku - dragon ball Z, goku,dragon ball,dragon ball Z,personaje,muñeco,caricatura,manga,plus','idLink':'214931'},
  { 'codigo':'00130','nombre':'GokuMicro-es','descripcion':'Goku mini','etiquetas':'goku mini, goku, dragon ball,personaje,mini,muñeco,caricatura','idLink':'214930'},
  { 'codigo':'00131','nombre':'Grinch20cm-es','descripcion':'Grinch 20cm','etiquetas':'grinch 20cm,grinch,20cm,personaje,navideño,navidad,pelicula,película,plus','idLink':'214934'},
  { 'codigo':'00132','nombre':'HaditaLollipop-es','descripcion':'Hadita Lollipop','etiquetas':'hadita lollipop,hadita,hada,lollipop,doll,muñeca','idLink':'214935'},
  { 'codigo':'00133','nombre':'HarryPotter-es','descripcion':'HarryPotter','etiquetas':'harry potter,harry,potter,personaje,muñeco,película,pelicula','idLink':'214936'},
  { 'codigo':'00134','nombre':'HarryStyles-es','descripcion':'Harry Styles','etiquetas':'harry styles,harry,styles,muñeco,mini','idLink':'214938'},
  { 'codigo':'00135','nombre':'HelloKittyAbeja-es','descripcion':'Hello Kitty Abeja','etiquetas':'hello kitty abeja,hello kitty,hello,kitty,personaje,abeja,gata,caricatura','idLink':'214937'},
  { 'codigo':'00136','nombre':'HeyArnoldYSusAmigos-es','descripcion':'Hey Arnold y sus amigos','etiquetas':'hey arnold y sus amigos,hey arnold,arnold,amigos,personaje,caricatura,plus','idLink':'214940'},
  { 'codigo':'00137','nombre':'HombreArana-es','descripcion':'Hombre Araña','etiquetas':'hombre araña,hombre,araña,personaje,mini,pelicula,película,spiderman,comic,personaje','idLink':'214939'},
  { 'codigo':'00138','nombre':'HulkAmigo-es','descripcion':'Hulk amigo','etiquetas':'hulk amigo,hulk,amigo,muñeco,pelicula,comic,personaje','idLink':'214942'},
  { 'codigo':'00139','nombre':'Hulk-es','descripcion':'Hulk mini','etiquetas':'hulk mini,hulk,mini,muñeco,comic,pelicula,personaje','idLink':'214941'},
  { 'codigo':'00140','nombre':'JackSparrow-es','descripcion':'Jack Sparrow','etiquetas':'jack sparrow,jack,sparrow,piratas del caribe,pirata,personaje,pelicula,película,plus','idLink':'214947'},
  { 'codigo':'00141','nombre':'JackSparrowPiratasDelCaribe-es','descripcion':'Jack Sparrow - Piratas del Caribe','etiquetas':'jack sparrow - piratas del caribe,jack sparrow,piratas del caribe, pirata, personaje,pelicula,película','idLink':'214943'},
  { 'codigo':'00142','nombre':'JirafaChataigne-es','descripcion':'Jirafa Chataigne','etiquetas':'jirafa chataigne,jirafa,chataigne','idLink':'214944'},
  { 'codigo':'00143','nombre':'JirafaGigi-es','descripcion':'Jirafa Gigi','etiquetas':'jirafa gigi,jirafa,gigi','idLink':'214945'},
  { 'codigo':'00144','nombre':'JirafaVainilla-es','descripcion':'Jirafa Vainilla','etiquetas':'jirafa vainilla,jirafa,vainilla,mini','idLink':'214946'},
  { 'codigo':'00145','nombre':'Jirafita-es','descripcion':'Jirafita','etiquetas':'jirafita,jirafa,baby,bebé,bebe','idLink':'214948'},
  { 'codigo':'00146','nombre':'Knitting-es','descripcion':'Niña tejida','etiquetas':'niña tejida,niña,tejida,knitting,doll,muñeca','idLink':'214949'},
  { 'codigo':'00147','nombre':'LeonAlanPlus-es','descripcion':'León Alan','etiquetas':'león alan,león,leon,alan,Plus','idLink':'214832'},
  { 'codigo':'00148','nombre':'Leon-es','descripcion':'León','etiquetas':'león,leon,chico','idLink':'215180'},
  { 'codigo':'00149','nombre':'LeonTyrion-es','descripcion':'León Tyrion','etiquetas':'león tyrion,león,leon,tyrion','idLink':'215039'},
  { 'codigo':'00150','nombre':'Letras-es','descripcion':'Letras','etiquetas':'letras,letra','idLink':'214951'},
  { 'codigo':'00151','nombre':'LlaveroCorazón-es','descripcion':'Corazón Llavero','etiquetas':'corazón llavero,corazón,corazon,llavero,mini','idLink':'214950'},
  { 'codigo':'00152','nombre':'Llaveros6Animalitos-es','descripcion':'Llaveros animalitos','etiquetas':'llaveros animalitos,llaveros,llavero,animalitos,animalito,mini','idLink':'214952'},
  { 'codigo':'00153','nombre':'LlaveroStitch-es','descripcion':'Llavero Stitch','etiquetas':'llavero stitch,llavero,stitch,mini,caricatura,personaje','idLink':'214953'},
  { 'codigo':'00154','nombre':'LlaveroTortuga-es','descripcion':'Llavero tortuga','etiquetas':'llavero tortuga,llavero,tortuga,mini','idLink':'217069'},
  { 'codigo':'00155','nombre':'Lorito-es','descripcion':'Lorito','etiquetas':'lorito,loro,ave','idLink':'214957'},
  { 'codigo':'00156','nombre':'LucaYSusAmigos-es','descripcion':'Luca y sus amigos','etiquetas':'Luca y sus amigos,Luca,amigos,amigo,personaje,caricatura,animado','idLink':'214955'},
  { 'codigo':'00157','nombre':'MafaldaMini-es','descripcion':'Mafalda mini','etiquetas':'mafalda mini,mafalda,mini,personaje,caricatura','idLink':'217049'},
  { 'codigo':'00158','nombre':'MafaldaPlus-es','descripcion':'Mafalda','etiquetas':'mafalda,personaje,plus,caricatura','idLink':'214959'},
  { 'codigo':'00159','nombre':'MantaUnicornio-es','descripcion':'Manta Unicornio','etiquetas':'manta unicornio,manta,unicornio','idLink':'214958'},
  { 'codigo':'00160','nombre':'Mantel6-es','descripcion':'Tapete con personajes','etiquetas':'tapete con personajes,tapete,animales,doll,muñeca,manta','idLink':'214962'},
  { 'codigo':'00161','nombre':'MarioBrosMini-es','descripcion':'Mario Bros mini','etiquetas':'mario bros mini,mario bros,mario,bros,mini,personaje, gamer,videojuego,plus','idLink':'214961'},
  { 'codigo':'00162','nombre':'Minions3-es','descripcion':'Minions','etiquetas':'minions,caricatura,animado,3','idLink':'214964'},
  { 'codigo':'00163','nombre':'Minnie-es','descripcion':'Minnie','etiquetas':'minnie,personaje,caricatura ratón,raton','idLink':'214965'},
  { 'codigo':'00164','nombre':'MunecoDeNieve-es','descripcion':'Muñeco de nieve','etiquetas':'muñeco de nieve,muñeco,nieve,snowman,navidad,navideño','idLink':'214968'},
  { 'codigo':'00165','nombre':'MunecoDeNievePeque-es','descripcion':'Muñeco de nieve chico','etiquetas':'muñeco de nieve chico,muñeco de nieve,muñeco,nieve,snowman,chico,navidad,navideño','idLink':'217028'},
  { 'codigo':'00166','nombre':'MunecoGilbert-es','descripcion':'Gilbert','etiquetas':'gilbert,muñeco,chico','idLink':'214970'},
  { 'codigo':'00167','nombre':'MunecoLuffy-es','descripcion':'Luffy','etiquetas':'luffy,muñeco','idLink':'214971'},
  { 'codigo':'00168','nombre':'MunecoSen-es','descripcion':'Sen','etiquetas':'sen,muñeco','idLink':'214974'},
  { 'codigo':'00169','nombre':'Nacimiento5-es','descripcion':'Nacimiento 5 piezas','etiquetas':'nacimiento 5 piezas,nacimiento,5 piezas,navidad,navideño,religión','idLink':'214973'},
  { 'codigo':'00170','nombre':'Naruto-es','descripcion':'Naruto','etiquetas':'naruto,personaje,muñeco,caricatura,manga,plus','idLink':'214976'},
  { 'codigo':'00171','nombre':'Nepe-es','descripcion':'Pene','etiquetas':'pene,nepe,sexo','idLink':'214975'},
  { 'codigo':'00172','nombre':'NinoJesus-es','descripcion':'Divino Niño','etiquetas':'divino niño jesús,divino,niño,jesús,religión,religion,plus','idLink':'217059'},
  { 'codigo':'00173','nombre':'NinoRopaTenisGorra-es','descripcion':'niño con outfit','etiquetas':'niño con outfit,niño,muñeco,outfit,ropa,tenis,gorra','idLink':'214978'},
  { 'codigo':'00174','nombre':'Nube-es','descripcion':'nube','etiquetas':'nube,mini','idLink':'214979'},
  { 'codigo':'00175','nombre':'Osita-es','descripcion':'osita bailarina','etiquetas':'osita bailarina,osita,bailarina,oso','idLink':'214981'},
  { 'codigo':'00176','nombre':'OsitaPijama-es','descripcion':'osita con pijama','etiquetas':'osita con pijama,osita,oso,pijama','idLink':'215160'},
  { 'codigo':'00177','nombre':'OsitoBoboo-en','descripcion':'osito Boboo','etiquetas':'osito Boboo,osito,Boboo,oso,picnic,chico','idLink':'215162'},
  { 'codigo':'00178','nombre':'OsitoPijama-es','descripcion':'osito con pijama','etiquetas':'osito con pijama,osito,pijama,oso,bonito','idLink':'215165'},
  { 'codigo':'00179','nombre':'OsoBearny-es','descripcion':'oso Bearny','etiquetas':'oso bearny,oso,bearny,plus','idLink':'215159'},
  { 'codigo':'00180','nombre':'OsoConCorazon-es','descripcion':'oso con corazón','etiquetas':'oso con corazón,oso,corazón,mini','idLink':'214982'},
  { 'codigo':'00181','nombre':'OsoGigante-es','descripcion':'oso gigante','etiquetas':'oso gigante,oso,gigante,grande','idLink':'215167'},
  { 'codigo':'00182','nombre':'OsoGorro-es','descripcion':'oso con gorro','etiquetas':'oso con gorro,oso,gorro,bonito','idLink':'215157'},
  { 'codigo':'00183','nombre':'OsoOutfit-es','descripcion':'oso y outfit','etiquetas':'oso y outfit,oso,outfit','idLink':'214986'},
  { 'codigo':'00184','nombre':'OsoPaddington-es','descripcion':'oso Paddington','etiquetas':'oso,paddington,libro','idLink':'217003'},
  { 'codigo':'00185','nombre':'OsoPandaPlus-es','descripcion':'oso panda','etiquetas':'oso panda,oso,panda,plus,bonito','idLink':'214984'},
  { 'codigo':'00186','nombre':'OsoPandaSusie-es','descripcion':'osita panda Susie','etiquetas':'osita panda susie,osita,panda,susie,bonito','idLink':'214983'},
  { 'codigo':'00187','nombre':'OsoTeddyYOutfits-es','descripcion':'oso Teddy y outfits','etiquetas':'oso teddy y outfits,oso,teddy,outfits,outfit','idLink':'217051'},
  { 'codigo':'00188','nombre':'Outfit40cm-es','descripcion':'outfit para animalito de 40cm','etiquetas':'outfit para animalito de 40cm,outfit,animalito,animal,40cm','idLink':'214985'},
  { 'codigo':'00189','nombre':'OvejitaHilos-es','descripcion':'ovejita hilos','etiquetas':'ovejita hilos,ovejita,hilos,oveja','idLink':'214990'},
  { 'codigo':'00190','nombre':'OvejitaLucera-es','descripcion':'ovejita Lucera','etiquetas':'ovejita lucera,ovejita,lucera,mini,oveja','idLink':'214988'},
  { 'codigo':'00191','nombre':'OvejitaMicro-es','descripcion':'ovejita','etiquetas':'ovejita,llavero,oveja','idLink':'214992'},
  { 'codigo':'00192','nombre':'PajaroLoco-es','descripcion':'Pájaro Loco','etiquetas':'pájaro loco,pájaro,pajaro,loco,caricatura,personaje','idLink':'217063'},
  { 'codigo':'00193','nombre':'Payaso40cm-es','descripcion':'payaso 40cm','etiquetas':'payaso 40cm,payaso,40cm,muñeco,colorido','idLink':'214996'},
  { 'codigo':'00194','nombre':'PayasoDulce-es','descripcion':'payaso dulce','etiquetas':'payaso dulce,payaso,dulce,muñeco,colorido','idLink':'214997'},
  { 'codigo':'00195','nombre':'Payaso-es','descripcion':'payaso pachón','etiquetas':'payaso pachón,payaso,pachón,pachon,muñeco,colorido','idLink':'214994'},
  { 'codigo':'00196','nombre':'PayasoSherbet-es','descripcion':'payaso Sherbet','etiquetas':'payaso sherbet,payaso,sherbet,muñeco','idLink':'214998'},
  { 'codigo':'00197','nombre':'PebbelsYBamBam-es','descripcion':'Pebbels y Bam Bam - Los Picapiedra','etiquetas':'pebbels y bam bam - los picapiedra,pebbels,bam bam,los picapiedra,picapiedra,muñeco,caricatura,bonito,personaje','idLink':'215001'},
  { 'codigo':'00198','nombre':'PebblesPicapiedra-es','descripcion':'pebbles Picapiedra','etiquetas':'pebbles picapiedra,pebbles,los picapiedra,picapiedra,muñeco,caricatura,personaje','idLink':'214999'},
  { 'codigo':'00199','nombre':'PeppaPigenPijamas-es','descripcion':'Peppa Pig en pijamas','etiquetas':'peppa pig en pijamas,peppa,pig,pijamas,cochino,cerdo,caricatura,personaje','idLink':'215000'},
  { 'codigo':'00200','nombre':'Perritos-es','descripcion':'Perritos','etiquetas':'perritos,perro,chihuahua,pastor alemán,pastor,alemán,aleman','idLink':'215005'},
  { 'codigo':'00201','nombre':'PerroPug-es','descripcion':'perro Pug','etiquetas':'perro pug,perro,pug','idLink':'215004'},
  { 'codigo':'00202','nombre':'PerroPugOjon-es','descripcion':'perro Pug ojón','etiquetas':'perro pug ojón,perro,pug,ojón,ojon','idLink':'215003'},
  { 'codigo':'00203','nombre':'PinochoArticulado-es','descripcion':'Pinocho articulado','etiquetas':'pinocho articulado,pinocho,articulado,caricatura,personaje','idLink':'215007'},
  { 'codigo':'00204','nombre':'PocoyoYNina-es','descripcion':'Pocoyó y Nina','etiquetas':'pocoyó y nina,pocoyó,pocoyo,nina,caricatura,animado','idLink':'215008'},
  { 'codigo':'00205','nombre':'PrincipitoLunaZoRosa-es','descripcion':'El Principito, luna, zorro y rosa en frasco','etiquetas':'el principito,principito,luna,zorro,rosa en frasco,rosa,frasco,libro','idLink':'215011'},
  { 'codigo':'00206','nombre':'PugRotSnaHus-es','descripcion':'Pug, Rottweiler, Schnauzer y Husky','etiquetas':'pug, rottweiler, schnauzer y husky perro','idLink':'215014'},
  { 'codigo':'00207','nombre':'PulpoLila-es','descripcion':'pulpo','etiquetas':'pulpo,lila','idLink':'215012'},
  { 'codigo':'00208','nombre':'PVZCarnivora-es','descripcion':'planta carnívora - PVZ','etiquetas':'planta carnívora - pvz,planta,carnívora,pvz, gamer,videojuego,personaje','idLink':'215013'},
  { 'codigo':'00209','nombre':'PVZGirasol-es','descripcion':'girasol - PVZ','etiquetas':'girasol - pvz ,girasol,pvz,gamer,videojuego,plantas contra zombies,personaje','idLink':'214927'},
  { 'codigo':'00210','nombre':'PVZombi-es','descripcion':'zombi - PVZ','etiquetas':'zombi - pvz,zombi,pvz,gamer,videojuego,plantas contra zombies,personaje','idLink':'215018'},
  { 'codigo':'00211','nombre':'RanaReneBB30cm-es','descripcion':'rana René baby 30cm','etiquetas':'rana rené baby 30cm,rana,rené,rene,baby,bebé,bebe,30cm,película,personaje','idLink':'215175'},
  { 'codigo':'00212','nombre':'RanaTima-es','descripcion':'rana Tima','etiquetas':'rana tima,rana,tima','idLink':'215035'},
  { 'codigo':'00213','nombre':'RatonIman-es','descripcion':'imán Ratón','etiquetas':'imán ratón,imán,iman,ratón,raton,nevera,refri','idLink':'215017'},
  { 'codigo':'00214','nombre':'RenoHarry-es','descripcion':'reno Harry','etiquetas':'reno harry,reno,harry,navidad,navideño','idLink':'215019'},
  { 'codigo':'00215','nombre':'RenoNavideno-es','descripcion':'reno navideño','etiquetas':'reno,navideño,navidad','idLink':'215020'},
  { 'codigo':'00216','nombre':'RickSanchez-es','descripcion':'Rick Sánchez','etiquetas':'rick sánchez,rick,sánchez,sanchez,caricatura,personaje,plus','idLink':'215024'},
  { 'codigo':'00217','nombre':'RosaAbierta-es','descripcion':'rosa abierta','etiquetas':'rosa abierta,rosa,abierta,flor','idLink':'215021'},
  { 'codigo':'00218','nombre':'RosaCerrada-es','descripcion':'rosa cerrada','etiquetas':'rosa cerrada,rosa,cerrada,flor','idLink':'215022'},
  { 'codigo':'00219','nombre':'RosAmarilla-es','descripcion':'rosa amarilla','etiquetas':'rosa amarilla,rosa,amarilla,flor','idLink':'215023'},
  { 'codigo':'00220','nombre':'Rosas-es','descripcion':'rosa','etiquetas':'rosa,flor','idLink':'215025'},
  { 'codigo':'00221','nombre':'SerpienteGde-es','descripcion':'serpiente grande','etiquetas':'serpiente grande,serpiente,grande','idLink':'215026'},
  { 'codigo':'00222','nombre':'Silvestre-es','descripcion':'Silvestre','etiquetas':'silvestre,caricatura,personaje','idLink':'217068'},
  { 'codigo':'00223','nombre':'SnorlaxPokemon46cm-es','descripcion':'Snorlax Pokémon 46cm','etiquetas':'snorlax pokémon 46cm,snorlax,pokémon,pokemon,46cm,grande,personaje','idLink':'215029'},
  { 'codigo':'00224','nombre':'SoldadoJuegoDelCalamar-es','descripcion':'soldado Juego del Calamar','etiquetas':'soldado juego del calamar,soldado,juego,calamar,llavero,chico, serie,bonito,personaje','idLink':'215028'},
  { 'codigo':'00225','nombre':'SonajeroConejito-es','descripcion':'sonajero conejito','etiquetas':'sonajero conejito,sonajero,conejito,conejo','idLink':'215030'},
  { 'codigo':'00226','nombre':'SonajeroJirafa-es','descripcion':'sonajero jirafa','etiquetas':'sonajero jirafa,sonajero,jirafa,free,gratuito','idLink':'215031'},
  { 'codigo':'00227','nombre':'SonajeroMariquitaRochi-es','descripcion':'sonajero mariquita Rochi','etiquetas':'sonajero mariquita rochi,sonajero,mariquita,rochi','idLink':'215032'},
  { 'codigo':'00228','nombre':'SonicKnuckles-es','descripcion':'Sonic y Knuckles','etiquetas':'sonic y knuckles,sonic,knuckles,personaje,plus','idLink':'215033'},
  { 'codigo':'00229','nombre':'SpidermanConYSinMascara-es','descripcion':'Hombre Araña cabeza con y sin máscara','etiquetas':'hombre araña cabeza con y sin máscara,hombre araña,hombre,araña,cabeza,máscara,spiderman,comic,personaje','idLink':'215037'},
  { 'codigo':'00230','nombre':'Tulipanes-es','descripcion':'tulipán plus','etiquetas':'tulipán plus,tulipán,tulipan,plus,bonito,flor','idLink':'215036'},
  { 'codigo':'00231','nombre':'UnicornioBetty-es','descripcion':'unicornio Betty','etiquetas':'unicornio betty,unicornio,betty','idLink':'215041'},
  { 'codigo':'00232','nombre':'UnicornioMicro-es','descripcion':'unicornio mini','etiquetas':'unicornio mini,unicornio,mini','idLink':'215040'},
  { 'codigo':'00233','nombre':'UnicornioMini-es','descripcion':'unicornio','etiquetas':'unicornio','idLink':'215038'},
  { 'codigo':'00234','nombre':'UnicornioPegaso-es','descripcion':'unicornio pegaso','etiquetas':'unicornio pegaso,unicornio,pegaso','idLink':'215042'},
  { 'codigo':'00235','nombre':'VeranoSietePatrones-es','descripcion':'Edición verano','etiquetas':'edición verano,edición,verano,flamingo,conejo,vaca,caballito de mar,caballo de mar,caballo,gato,sirena,muñeca,doll','idLink':'215027'},
  { 'codigo':'00236','nombre':'WandaPadrinosMagicos-es','descripcion':'Wanda - Los Padrinos Mágicos','etiquetas':'wanda - los padrinos mágicos,wanda,los padrinos mágicos,padrinos mágicos,padrinos magicos, caricatura, personaje','idLink':'215044'},
  { 'codigo':'00237','nombre':'Winnie-es','descripcion':'Winnie Pooh','etiquetas':'winnie pooh,winnie,pooh,libro,caricatura,mini,personaje','idLink':'215045'},
  { 'codigo':'00238','nombre':'Yoda-es','descripcion':'Yoda','etiquetas':'yoda viejo,yoda,viejo,película,personaje','idLink':'215178'},  
];