const catalogoPatrones = [
  {'codigo':'0001', 
  'nombre': 'AbrazaCortinasCochino-es', 
  'descripcion': 'abrazacortinas cochino'},
  {'codigo':'0002', 
  'nombre': 'AbrazaCortinasConejo-es', 
  'descripcion': 'abrazacortinas conejo'},
  {'codigo':'0003', 
  'nombre': 'AbrazaCortinasDinosaurio-es', 
  'descripcion': 'abrazacortinas dinosaurio'},
  {'codigo':'0004', 
  'nombre': 'AbrazaCortinasFridaKalho-es', 
  'descripcion': 'abrazacortinas frida kalho'},
  {'codigo':'005', 
  'nombre': 'AbrazaCortinasMono-es', 
  'descripcion': 'abrazacortinas mono'},
  {'codigo':'0006', 
  'nombre': 'AbrazaCortinasTigre-es', 
  'descripcion': 'abrazacortinas tigre'},
  {'codigo':'0007', 
  'nombre': 'AguacatesEnamorados-es', 
  'descripcion': 'aguacates enamorados'},
  {'codigo':'0008', 
  'nombre': 'Ajolotes-es', 
  'descripcion': 'ajolotes'},
  {'codigo':'0009', 
  'nombre': 'AlfileteroTotoro-es', 
  'descripcion': 'alfiletero totoro'},
  {'codigo':'0010', 
  'nombre': 'Amiguruminis-es', 
  'descripcion': 'amiguruminis-es'},
  {'codigo':'0011', 
  'nombre': 'AngelCerditaPippa-es', 
  'descripcion': 'angel cerdita pippa'},
  {'codigo':'0012', 
  'nombre': 'Angelitos-es', 
  'descripcion': 'angelitos'},
  {'codigo':'0013', 
  'nombre': 'AngelOsoTeddy-es', 
  'descripcion': 'angel oso teddy'},
  {'codigo':'0014', 
  'nombre': 'Animatronicos4FNAF-es', 
  'descripcion': 'animatronicos 4FNAF'},
  {'codigo':'0015', 
  'nombre': 'BabyBaphyDemon-es', 
  'descripcion': 'baby baphy demon'},
  {'codigo':'0016', 
  'nombre': 'BabyDisney6-es', 
  'descripcion': 'baby disney 6 personajes'},
  {'codigo':'0017', 
  'nombre': 'BabyYodaCorazonMini-es', 
  'descripcion': 'Bbby yoda con corazon mini'},
  {'codigo':'0018', 
  'nombre': 'BabyYoda-es', 
  'descripcion': 'baby yoda'},
  {'codigo':'0019', 
  'nombre': 'BaphometDemon-es', 
  'descripcion': 'baphomet demon'},
  {'codigo':'0020', 
  'nombre': 'BaseConejoMila32cm-es', 
  'descripcion': 'base conejo mila 32cm'},
]