const catalogoPatrones = [
  { 'codigo':'00001','nombre':'AbrazaCortinasCochino-es','descripcion':'abrazacortinas cochino','etiquetas':'abrazacortinas cochino'},
  { 'codigo':'00002','nombre':'AbrazaCortinasConejo-es','descripcion':'abrazacortinas conejo','etiquetas':'abrazacortinas conejo'},
  { 'codigo':'00003','nombre':'AbrazaCortinasDinosaurio-es','descripcion':'abrazacortinas dinosaurio','etiquetas':'abrazacortinas dinosaurio'},
  { 'codigo':'00004','nombre':'AbrazaCortinasFridaKalho-es','descripcion':'abrazacortinas frida kalho','etiquetas':'abrazacortinas frida kalho'},
  { 'codigo':'00005','nombre':'AbrazaCortinasMono-es','descripcion':'abrazacortinas mono','etiquetas':'abrazacortinas mono'},
  { 'codigo':'00006','nombre':'AbrazaCortinasTigre-es','descripcion':'abrazacortinas tigre','etiquetas':'abrazacortinas tigre'},
  { 'codigo':'00007','nombre':'AguacatesEnamorados-es','descripcion':'aguacates enamorados','etiquetas':'aguacates enamorados'},
  { 'codigo':'00008','nombre':'Ajolotes-es','descripcion':'ajolotes','etiquetas':'ajolotes'},
  { 'codigo':'00009','nombre':'AlfileteroTotoro-es','descripcion':'alfiletero totoro','etiquetas':'alfiletero totoro'},
  { 'codigo':'00010','nombre':'Amiguruminis-es','descripcion':'amiguruminis','etiquetas':'amiguruminis miniatura'},
  { 'codigo':'00011','nombre':'AngelCerditaPippa-es','descripcion':'angel cerdita pippa','etiquetas':'angel cerdita pippa'},
  { 'codigo':'00012','nombre':'Angelitos-es','descripcion':'angelitos','etiquetas':'angelitos'},
  { 'codigo':'00013','nombre':'AngelOsoTeddy-es','descripcion':'angel oso teddy','etiquetas':'angel oso teddy'},
  { 'codigo':'00014','nombre':'Animatronicos4FNAF-es','descripcion':'animatronicos 4FNAF','etiquetas':'animatronicos 4FNAF'},
  { 'codigo':'00015','nombre':'BabyBaphyDemon-es','descripcion':'baby baphy demon','etiquetas':'baby baphy demon'},
  { 'codigo':'00016','nombre':'BabyDisney6-es','descripcion':'baby disney 6 personajes','etiquetas':'baby disney 6 personajes caricatura'},
  { 'codigo':'00017','nombre':'BabyYodaCorazonMini-es','descripcion':'Baby Yoda con corazon mini','etiquetas':'Baby Yoda con corazon mini película'},
  { 'codigo':'00018','nombre':'BabyYoda-es','descripcion':'baby Yoda','etiquetas':'baby Yoda película'},
  { 'codigo':'00019','nombre':'BaphometDemon-es','descripcion':'baphomet demon','etiquetas':'baphomet demon'},
  { 'codigo':'00020','nombre':'BaseConejoMila32cm-es','descripcion':'base conejo mila 32cm','etiquetas':'base conejo mila 32cm'},
  { 'codigo':'00021','nombre':'BebeConChupon-es','descripcion':'bebe con chupon','etiquetas':'Bebe con chupon doll muñeca baby'},
  { 'codigo':'00022','nombre':'BebeDisfrazJirafa-es','descripcion':'bebe con disfraz de jirafa','etiquetas':'bebe con disfraz de jirafa doll muñeca outfit baby'},
  { 'codigo':'00023','nombre':'BebeDragon-es','descripcion':'bebe dragon','etiquetas':'bebe dragon baby'},
  { 'codigo':'00024','nombre':'BlancaNieves-es','descripcion':'blanca nieves','etiquetas':'blanca nieves doll muñeca princesa caricatura'},
  { 'codigo':'00025','nombre':'Bodoque-es','descripcion':'bodoque','etiquetas':'bodoque serie'},
  { 'codigo':'00026','nombre':'BolsoMono-es','descripcion':'bolso mono','etiquetas':'bolso mono bolsa monito bulto'},
  { 'codigo':'00027','nombre':'BooMonsters-es','descripcion':'boo monsters','etiquetas':'boo monsters inc outfit caricatura animado'},
  { 'codigo':'00028','nombre':'Brujita-es','descripcion':'brujita','etiquetas':'brujita halloween'},
  { 'codigo':'00029','nombre':'Bts7-es','descripcion':'bts 7 personajes','etiquetas':'Bts 7 personajes'},
  { 'codigo':'00030','nombre':'BuhitaVestido-es','descripcion':'buhita con vestido','etiquetas':'buhita con vestido outfit'},
  { 'codigo':'00031','nombre':'BuhoSujetaPuertas-es','descripcion':'buho sujetapuertas','etiquetas':'buho sujetapuertas'},
  { 'codigo':'00032','nombre':'BulldogPuppy16x14cm-es','descripcion':'bulldog puppy 16 x 14 cm','etiquetas':'bulldog puppy 16cm x 14 cm'},
  { 'codigo':'00033','nombre':'BulmaDragonBall-es','descripcion':'bulma dragon ball','etiquetas':'bulma dragon ball doll muñeca caricatura manga anime'},
  { 'codigo':'00034','nombre':'BuzzLightyear-es','descripcion':'buzz lightyear','etiquetas':'buzz lightyear muñeco caricatura animado'},
  { 'codigo':'00035','nombre':'CabezasDeGato4-es','descripcion':'cabeza de gato','etiquetas':'4 cabezas de gato'},
  { 'codigo':'00036','nombre':'Cactus2-es','descripcion':'higo chumbo y cactus classic','etiquetas':'higo chumbo y cactus classic'},
  { 'codigo':'00037','nombre':'Cactus3-es','descripcion':'3 tipos de cactus','etiquetas':'3 cactus'},
  { 'codigo':'00038','nombre':'Cactus9pequenos-es','descripcion':'9 tipos de cactus','etiquetas':'9 cactus'},
  { 'codigo':'00039','nombre':'CactusEnMacetaDeConejo-es','descripcion':'cactus en maceta de conejo','etiquetas':'cactus en maceta de conejo'},
  { 'codigo':'00040','nombre':'CandYMint-es','descripcion':'Candy y Mint','etiquetas':'Candy y Mint doll muñeca'},
  { 'codigo':'00041','nombre':'CaperucitaRoja-es','descripcion':'Caperucita Roja','etiquetas':'Caperucita Roja doll muñeca libro'},
  { 'codigo':'00042','nombre':'CarlitosRugrats-es','descripcion':'Carlitos Rugrats','etiquetas':'Carlitos Rugrats muñeco caricatura'},
  { 'codigo':'00043','nombre':'CarlYEllieUps-es','descripcion':'Carl y Ellie - Ups','etiquetas':'Carl y Ellie Ups caricatura animado'},
  { 'codigo':'00044','nombre':'Catherina-es','descripcion':'Catherina','etiquetas':'Catherina doll muñeca'},
  { 'codigo':'00045','nombre':'CincoPatrones-es','descripcion':'5 Patrones kinder','etiquetas':'5 Patrones kinder ratón dinosaurio cocodrilo payaso crayolas'},
  { 'codigo':'00046','nombre':'CocodriloConrad-es','descripcion':'cocodrilo Conrad','etiquetas':'cocodrilo Conrad con aro'},
  { 'codigo':'00047','nombre':'ComeGalletas-es','descripcion':'Comegalletas Plaza Sésamo','etiquetas':'Comegalletas Plaza Sésamo serie'},
  { 'codigo':'00048','nombre':'ConejaAlma-es','descripcion':'coneja Alma','etiquetas':'coneja Alma'},
  { 'codigo':'00049','nombre':'ConejaBonny-es','descripcion':'coneja Bonny','etiquetas':'coneja Bonny'},
  { 'codigo':'00050','nombre':'ConejaEsther-es','descripcion':'coneja Esther','etiquetas':'coneja Esther'},
  { 'codigo':'00051','nombre':'ConejaMaggie-es','descripcion':'coneja Maggie','etiquetas':'coneja Maggie'},
  { 'codigo':'00052','nombre':'ConejaRusa-es','descripcion':'coneja Rusa','etiquetas':'coneja Rusa'},
  { 'codigo':'00053','nombre':'ConejaSophie-es','descripcion':'coneja Sophie','etiquetas':'coneja Sophie'},
  { 'codigo':'00054','nombre':'ConejaVestidoAzul-es','descripcion':'coneja vestido azul','etiquetas':'coneja vestido azul'},
  { 'codigo':'00055','nombre':'ConejitaAdriana-es','descripcion':'conejita Adriana','etiquetas':'conejita Adriana'},
  { 'codigo':'00056','nombre':'ConejitaConVestido-es','descripcion':'conejita con vestido','etiquetas':'conejita con vestido'},
  { 'codigo':'00057','nombre':'ConejitaMia-es','descripcion':'conejita Mia','etiquetas':'conejita Mia'},
  { 'codigo':'00058','nombre':'ConejoRaton33cm-es','descripcion':'conejo mameluco ratón 33 cm','etiquetas':'conejo mameluco ratón 33cm'},
  { 'codigo':'00059','nombre':'Corazon-es','descripcion':'corazón','etiquetas':'corazón'},
  { 'codigo':'00060','nombre':'CosmoPadrinosMagicos-es','descripcion':'Cosmo Padrinos Mágicos','etiquetas':'Cosmo Padrinos Mágicos muñeco caricaturas'},
  { 'codigo':'00061','nombre':'CostureroAbuela-es','descripcion':'costurero abuela','etiquetas':'costurero abuela doll muñeca'},
  { 'codigo':'00062','nombre':'CostureroGato-es','descripcion':'costurero gato','etiquetas':'costurero gato'},
  { 'codigo':'00063','nombre':'CruellaDeVil-es','descripcion':'Cruella de Vil','etiquetas':'Cruella de Vil doll muñeca película'},
  { 'codigo':'00064','nombre':'CuPigdo-es','descripcion':'Cupigdo','etiquetas':'Cupigdo cupido cerdo cochino chancho'},
  { 'codigo':'00065','nombre':'DinoColorido-es','descripcion':'dinosaurio azul','etiquetas':'dinosaurio azul colorido'},
  { 'codigo':'00066','nombre':'DinoJoaco-es','descripcion':'Dino Joaco','etiquetas':'Dino Joaco dinosaurio'},
  { 'codigo':'00067','nombre':'DinoKnotjira-es','descripcion':'Dino Knotjira','etiquetas':'Dino Knotjira corto animación'},
  { 'codigo':'00068','nombre':'DinoLucky-es','descripcion':'Dino Lucky','etiquetas':'Dino Lucky dinasaurio'},
  { 'codigo':'00069','nombre':'DiosHuitzilopochtli-es','descripcion':'Dios Huitzilopochtli','etiquetas':'Dios Huitzilopochtli Mexica guerra'},
  { 'codigo':'00070','nombre':'DiosMictlantecuhtli-es','descripcion':'Dios Mictlantecuhtli','etiquetas':'Dios Mictlantecuhtli Mexica muerte'},
  { 'codigo':'00071','nombre':'DiosQuetzalcoatl-es','descripcion':'Dios Quetzalcoatl','etiquetas':'Dios Quetzalcoatl Azteca'},
  { 'codigo':'00072','nombre':'DiosTlaloc-es','descripcion':'Dios Tlaloc','etiquetas':'Dios Tlaloc Mexica lluvia'},
  { 'codigo':'00073','nombre':'DollAliciaYConejo-es','descripcion':'Alicia y conejo','etiquetas':'Alicia y conejo doll muñeca'},
  { 'codigo':'00074','nombre':'DollAnastasia-es','descripcion':'Anastasia','etiquetas':'Anastasia doll muñeca elfa'},
  { 'codigo':'00075','nombre':'DollAnne-es','descripcion':'Anne','etiquetas':'Anne doll muñeca'},
  { 'codigo':'00076','nombre':'DollAutumn-es','descripcion':'Autumn','etiquetas':'Autumn doll muñeca'},
  { 'codigo':'00077','nombre':'DollBailarinasElLago-es','descripcion':'Bailarinas - El Lago de las sombras','etiquetas':'Bailarinas - El Lago de las sombras'},
  { 'codigo':'00078','nombre':'DollCandyCandy-es','descripcion':'Candy Candy','etiquetas':'Candy Candy doll muñeca caricaturas'},
  { 'codigo':'00079','nombre':'DollConejo-es','descripcion':'Muñeca con conejo','etiquetas':'Muñeca con conejo doll'},
  { 'codigo':'00080','nombre':'DollDulce-es','descripcion':'Dulce navideña','etiquetas':'Dulce muñeca doll navideño'},
  { 'codigo':'00081','nombre':'DollDulceNoa-es','descripcion':'Dulce Noa','etiquetas':'Dulce Noa doll muñeca'},
  { 'codigo':'00082','nombre':'DollElenaDeAvalor-es','descripcion':'Elena de Avalor','etiquetas':'Elena de Avalor doll muñeca'},
  { 'codigo':'00083','nombre':'DollEly-es','descripcion':'Ely','etiquetas':'Ely doll muñeca'},
  { 'codigo':'00084','nombre':'DollEvaYOto-es','descripcion':'Eva y Oto','etiquetas':'Eva y Oto doll muñeca oso'},
  { 'codigo':'00085','nombre':'DollFiona-es','descripcion':'Fiona','etiquetas':'Fiona carictura animada'},
  { 'codigo':'00086','nombre':'DollFridaKahloBaby-es','descripcion':'Frida Kahlo baby','etiquetas':'Frida Kahlo baby doll muñeca bebe'},
  { 'codigo':'00087','nombre':'DollFridaMini-es','descripcion':'Frida Kahlo mini','etiquetas':'Frida Kahlo mini doll muñeca'},
  { 'codigo':'00088','nombre':'DollGraduada-es','descripcion':'Graduada','etiquetas':'Graduada doll muñeca'},
  { 'codigo':'00089','nombre':'DollIcelyn-es','descripcion':'Icelyn','etiquetas':'Icelyn doll muñeca'},
  { 'codigo':'00090','nombre':'DollKiki-es','descripcion':'Kiki mini','etiquetas':'Kiki mini doll muñeca'},
  { 'codigo':'00091','nombre':'DollLalkaYChloe-es','descripcion':'Lalka y Chloe','etiquetas':'Lalka y Chloe doll muñeca'},
  { 'codigo':'00092','nombre':'DollLilly-es','descripcion':'Lilly','etiquetas':'Lilly doll muñeca'},
  { 'codigo':'00093','nombre':'DollMariaFlorDePina-es','descripcion':'Maria Flor de Piña','etiquetas':'Maria Flor de Piña doll muñeca colorido'},
  { 'codigo':'00094','nombre':'DollMariaJulia-es','descripcion':'Maria Julia','etiquetas':'Maria Julia doll muñeca'},
  { 'codigo':'00095','nombre':'DollMercedita6-es','descripcion':'Mercedita 6 diseños','etiquetas':'Mercedita 6 diseños doll muñeca'},
  { 'codigo':'00096','nombre':'DollMoana-es','descripcion':'Moana','etiquetas':'Moana doll muñeca caricaturas animado'},
  { 'codigo':'00097','nombre':'DollMolly-es','descripcion':'Molly','etiquetas':'Molly doll muñeca'},
  { 'codigo':'00098','nombre':'DollNezuko-es','descripcion':'Nezuko Kimetsu','etiquetas':'Nezuko Kimetsu caricaturas anime'},
  { 'codigo':'00099','nombre':'DollNina-es','descripcion':'Nina','etiquetas':'Nina doll muñeca'},
  { 'codigo':'00100','nombre':'DollOhanaStich-es','descripcion':'Lilo y Stitch','etiquetas':'Lilo y Stitch doll muñeca miniatura'},
  { 'codigo':'00101','nombre':'DollPayasita-es','descripcion':'Payasita','etiquetas':'Payasita doll muñeca'},
  { 'codigo':'00102','nombre':'DollPrincesaRapunzel-es','descripcion':'Princesa Rapunzel','etiquetas':'Princesa Rapunzel doll muñeca'},
  { 'codigo':'00103','nombre':'DollRebeca-es','descripcion':'Rebeca','etiquetas':'Rebeca doll muñeca'},
  { 'codigo':'00104','nombre':'DollRinLinInuyasha-es','descripcion':'Rin Lin Inuyasha','etiquetas':'Rin Lin Inuyasha doll muñeca caricatura anime manga'},
  { 'codigo':'00105','nombre':'DollSakura-es','descripcion':'Sakura Haruno','etiquetas':'Sakura Haruno doll muñeca caricatura anime manga'},
  { 'codigo':'00106','nombre':'DollThuyAnh-es','descripcion':'Thuy Anh','etiquetas':'Thuy Anh doll muñeca'},
  { 'codigo':'00107','nombre':'DollTilda-es','descripcion':'Tilda','etiquetas':'Tilda doll muñeca bonito'},
  { 'codigo':'00108','nombre':'DollTurca-es','descripcion':'Turca','etiquetas':'Turca doll muñeca bonito'},
  { 'codigo':'00109','nombre':'DollUnicornioLol-es','descripcion':'Unicornio Lol','etiquetas':'Unicornio Lol doll muñeca coneja'},
  { 'codigo':'00110','nombre':'DollVioleta-es','descripcion':'Violeta la niña Pom Pom','etiquetas':'Violeta la niña Pom Pom doll muñeca'},
  { 'codigo':'00111','nombre':'DollZara-es','descripcion':'Zara','etiquetas':'Zara doll muñeca'},
  { 'codigo':'00112','nombre':'DollZoey-es','descripcion':'Zoey','etiquetas':'Zoey doll muñeca bonito'},
  { 'codigo':'00113','nombre':'DragonChimuelo-es','descripcion':'Chimuelo - Cómo entrenar a tu Dragón','etiquetas':'Chimuelo - Cómo entrenar a tu Dragón caricaturas animado'},
  { 'codigo':'00114','nombre':'DuendePachitoPlus-es','descripcion':'Duende Pachito','etiquetas':'Duende Pachito plus navidad'},
  { 'codigo':'00115','nombre':'EdicionSanValentin10-es','descripcion':'Edición San Valentín','etiquetas':'Edición San Valentín muñeco oso corazón perro ratón serpiente monito mono llavero mini'},
  { 'codigo':'00116','nombre':'ElefanteGris-es','descripcion':'Elefante Gris','etiquetas':'Elefante Gris plus bonito'},
  { 'codigo':'00117','nombre':'ElPrincipito-es','descripcion':'El Principito y Zorro','etiquetas':'El Principito y Zorro muñeco mini libro'},
  { 'codigo':'00118','nombre':'ElPrincipitoPlus-es','descripcion':'El Principito','etiquetas':'El Principito plus libro'},
  { 'codigo':'00119','nombre':'ElSombrereroLoco-es','descripcion':'El Sombrerero Loco','etiquetas':'El Sombrerero Loco muñeco'},
  { 'codigo':'00120','nombre':'FlashMamaGallina-es','descripcion':'Flash mini','etiquetas':'Flash mini'},
  { 'codigo':'00121','nombre':'FreddieMercury-es','descripcion':'FreddieMercury','etiquetas':'FreddieMercury'},
  { 'codigo':'00122','nombre':'FreddieMercuryIWantToBreakFree-es','descripcion':'Freddie Mercury I Want To Break Free','etiquetas':'Freddie Mercury I Want To Break Free muñeco mini'},
  { 'codigo':'00123','nombre':'GataMia-es','descripcion':'Gata Mía con corazón','etiquetas':'Gata Mía con corazón mini'},
  { 'codigo':'00124','nombre':'GatoGrisRealistaGde-es','descripcion':'Gato gris realista','etiquetas':'Gato gris realista'},
  { 'codigo':'00125','nombre':'GatoNavidad-es','descripcion':'Gato suéter rojo','etiquetas':'Gato suéter rojo'},
  { 'codigo':'00126','nombre':'Gerbera-es','descripcion':'Gerbera','etiquetas':'Gerbera gemma flor doll muñeca 28cm'},
  { 'codigo':'00127','nombre':'Girasol-es','descripcion':'Girasol','etiquetas':'Girasol flor'},
  { 'codigo':'00128','nombre':'Girasoles-es','descripcion':'Girasoles','etiquetas':'Girasoles flor'},
  { 'codigo':'00129','nombre':'Goku-es','descripcion':'Goku - Dragon ball Z','etiquetas':'Goku - Dragon ball Z muñeco caricatura manga'},
  { 'codigo':'00130','nombre':'GokuMicro-es','descripcion':'Goku mini','etiquetas':'Goku mini micro muñeco caricatura'},
  { 'codigo':'00131','nombre':'Grinch20cm-es','descripcion':'Grinch 20cm','etiquetas':'Grinch 20cm navidad pelicula'},
  { 'codigo':'00132','nombre':'HaditaLollipop-es','descripcion':'Hadita Lollipop','etiquetas':'Hadita Lollipop doll muñeca'},
  { 'codigo':'00133','nombre':'HarryPotter-es','descripcion':'HarryPotter','etiquetas':'HarryPotter muñeco pelicula'},
  { 'codigo':'00134','nombre':'HarryStyles-es','descripcion':'Harry Styles','etiquetas':'Harry Styles muñeco mini'},
  { 'codigo':'00135','nombre':'HelloKittyAbeja-es','descripcion':'Hello Kitty Abeja','etiquetas':'Hello Kitty Abeja gata caricatura'},
  { 'codigo':'00136','nombre':'HeyArnoldYSusAmigos-es','descripcion':'Hey Arnold y sus amigos','etiquetas':'Hey Arnold y sus amigos caricatura'},
  { 'codigo':'00137','nombre':'HombreArana-es','descripcion':'Hombre Araña','etiquetas':'Hombre Araña mini pelicula'},
  { 'codigo':'00138','nombre':'HulkAmigo-es','descripcion':'Hulk amigo','etiquetas':'Hulk amigo muñeco pelicula'},
  { 'codigo':'00139','nombre':'Hulk-es','descripcion':'Hulk mini','etiquetas':'Hulk mini muñeco pelicula'},
  { 'codigo':'00140','nombre':'JackSparrow-es','descripcion':'Jack Sparrow','etiquetas':'Jack Sparrow pelicula'},
  { 'codigo':'00141','nombre':'JackSparrowPiratasDelCaribe-es','descripcion':'Jack Sparrow - Piratas del Caribe','etiquetas':'Jack Sparrow - Piratas del Caribe pelicula'},
  { 'codigo':'00142','nombre':'JirafaChataigne-es','descripcion':'Jirafa Chataigne','etiquetas':'Jirafa Chataigne'},
  { 'codigo':'00143','nombre':'JirafaGigi-es','descripcion':'Jirafa Gigi','etiquetas':'Jirafa Gigi'},
  { 'codigo':'00144','nombre':'JirafaVainilla-es','descripcion':'Jirafa Vainilla','etiquetas':'Jirafa Vainilla mini'},
  { 'codigo':'00145','nombre':'Jirafita-es','descripcion':'Jirafita','etiquetas':'Jirafita baby bebé'},
  { 'codigo':'00146','nombre':'Knitting-es','descripcion':'Niña tejida','etiquetas':'Niña tejida Knitting doll muñeca'},
  { 'codigo':'00147','nombre':'LeonAlanPlus-es','descripcion':'León Alan','etiquetas':'Leon Alan Plus'},
  { 'codigo':'00148','nombre':'Leon-es','descripcion':'León','etiquetas':'Leon chico'},
  { 'codigo':'00149','nombre':'LeonTyrion-es','descripcion':'Leon Tyrion','etiquetas':'Leon Tyrion'},
  { 'codigo':'00150','nombre':'Letras-es','descripcion':'Letras','etiquetas':'Letras'},
  { 'codigo':'00151','nombre':'LlaveroCorazón-es','descripcion':'Corazón Llavero','etiquetas':'Corazón Llavero mini'},
  { 'codigo':'00152','nombre':'Llaveros6Animalitos-es','descripcion':'Llaveros animalitos','etiquetas':'Llaveros animalitos mini'},
  { 'codigo':'00153','nombre':'Llaveros7Winnie PoohYAmigos-es','descripcion':'Llaveros - Winnie Pooh y amigos','etiquetas':'Llaveros - Winnie Pooh y amigos mini caricatura'},
  { 'codigo':'00154','nombre':'LlaveroStitch-es','descripcion':'Llavero Stitch','etiquetas':'Llavero Stitch mini caricatura'},
  { 'codigo':'00155','nombre':'LlaveroTortuga-es','descripcion':'Llavero tortuga','etiquetas':'Llavero tortuga mini'},
  { 'codigo':'00156','nombre':'Lorito-es','descripcion':'Lorito','etiquetas':'Lorito loro ave'},
  { 'codigo':'00157','nombre':'LucaYSusAmigos-es','descripcion':'Luca y sus amigos','etiquetas':'Luca y sus amigos caricatura animado'},
  { 'codigo':'00158','nombre':'MafaldaMini-es','descripcion':'Mafalda mini','etiquetas':'Mafalda mini caricatura'},
  { 'codigo':'00159','nombre':'MafaldaPlus-es','descripcion':'Mafalda','etiquetas':'Mafalda plus caricatura'},
  { 'codigo':'00160','nombre':'MantaUnicornio-es','descripcion':'Manta Unicornio','etiquetas':'Manta Unicornio'},
  { 'codigo':'00161','nombre':'Mantel6-es','descripcion':'Tapete con personajes','etiquetas':'Tapete con personajes'},
  { 'codigo':'00162','nombre':'MarioBrosMini-es','descripcion':'Mario Bros mini','etiquetas':'Mario Bros mini gamer videojuego '},
  { 'codigo':'00163','nombre':'Minions3-es','descripcion':'Minions','etiquetas':'Minions caricatura animado'},
  { 'codigo':'00164','nombre':'Minnie-es','descripcion':'Minnie','etiquetas':'Minnie caricatura ratón'},
  { 'codigo':'00165','nombre':'MunecoDeNieve-es','descripcion':'Muñeco de nieve','etiquetas':'Muñeco de nieve'},
  { 'codigo':'00166','nombre':'MunecoDeNievePeque-es','descripcion':'Muneco de nieve chico','etiquetas':'Muneco de nieve chico'},
  { 'codigo':'00167','nombre':'MunecoGilbert-es','descripcion':'Gilbert','etiquetas':'Muñeco Gilbert chico'},
  { 'codigo':'00168','nombre':'MunecoLuffy-es','descripcion':'Luffy','etiquetas':'Muñeco Luffy'},
  { 'codigo':'00169','nombre':'MunecoSen-es','descripcion':'Sen','etiquetas':'Muñeco Sen'},
  { 'codigo':'00170','nombre':'Nacimiento5-es','descripcion':'Nacimiento 5 piezas','etiquetas':'Nacimiento navidad religión'},
  { 'codigo':'00171','nombre':'Naruto-es','descripcion':'Naruto','etiquetas':'Naruto muñeco caricatura manga'},
  { 'codigo':'00172','nombre':'Nepe-es','descripcion':'pene','etiquetas':'pene nepe sexo'},
  { 'codigo':'00173','nombre':'NinoJesus-es','descripcion':'Divino Nino','etiquetas':'Divino Nino Jesus religión'},
  { 'codigo':'00174','nombre':'NinoRopaTenisGorra-es','descripcion':'niño con outfit','etiquetas':'niño con outfit ropa tenis gorra'},
  { 'codigo':'00175','nombre':'Nube-es','descripcion':'nube','etiquetas':'nube mini'},
  { 'codigo':'00176','nombre':'Osita-es','descripcion':'osita bailarina','etiquetas':'osita bailarina oso'},
  { 'codigo':'00177','nombre':'OsitaPijama-es','descripcion':'osita con pijama','etiquetas':'osita con pijama oso'},
  { 'codigo':'00178','nombre':'OsitoBoboo-en','descripcion':'osito Boboo','etiquetas':'osito Boboo oso'},
  { 'codigo':'00179','nombre':'OsitoPijama-es','descripcion':'osito con pijama','etiquetas':'osito con pijama oso bonito'},
  { 'codigo':'00180','nombre':'OsoBearny-es','descripcion':'oso Bearny','etiquetas':'oso Bearny'},
  { 'codigo':'00181','nombre':'OsoConCorazon-es','descripcion':'oso con corazón','etiquetas':'oso con corazón mini'},
  { 'codigo':'00182','nombre':'OsoGigante-es','descripcion':'oso gigante','etiquetas':'oso gigante'},
  { 'codigo':'00183','nombre':'OsoGorro-es','descripcion':'oso con gorro','etiquetas':'oso con gorro bonito'},
  { 'codigo':'00184','nombre':'OsoOutfit-es','descripcion':'oso outfit','etiquetas':'oso outfit'},
  { 'codigo':'00185','nombre':'OsoPaddington-es','descripcion':'oso Paddington','etiquetas':'oso Paddington libro'},
  { 'codigo':'00186','nombre':'OsoPandaPlus-es','descripcion':'oso panda','etiquetas':'oso panda plus bonito'},
  { 'codigo':'00187','nombre':'OsoPandaSusie-es','descripcion':'osita panda Susie','etiquetas':'osita panda Susie'},
  { 'codigo':'00188','nombre':'OsoTeddyYOutfits-es','descripcion':'oso Teddy y outfits','etiquetas':'oso Teddy y outfits'},
  { 'codigo':'00189','nombre':'Outfit40cm-es','descripcion':'outfit para animalito de 40cm','etiquetas':'outfit para animalito de 40cm'},
  { 'codigo':'00190','nombre':'OvejitaHilos-es','descripcion':'ovejita hilos','etiquetas':'ovejita hilos oveja'},
  { 'codigo':'00191','nombre':'OvejitaLucera-es','descripcion':'ovejita Lucera','etiquetas':'ovejita Lucera mini'},
  { 'codigo':'00192','nombre':'OvejitaMicro-es','descripcion':'ovejita','etiquetas':'ovejita'},
  { 'codigo':'00193','nombre':'PajaroLoco-es','descripcion':'Pájaro Loco','etiquetas':'Pájaro Loco caricatura'},
  { 'codigo':'00194','nombre':'Payaso40cm-es','descripcion':'payaso 40cm','etiquetas':'payaso 40cm muñeco colorido'},
  { 'codigo':'00195','nombre':'PayasoDulce-es','descripcion':'payaso dulce','etiquetas':'payaso dulce muñeco colorido'},
  { 'codigo':'00196','nombre':'Payaso-es','descripcion':'payaso pachón','etiquetas':'payaso pachón muñeco colorido'},
  { 'codigo':'00197','nombre':'PayasoSherbet-es','descripcion':'payaso Sherbet','etiquetas':'payaso Sherbet muñeco'},
  { 'codigo':'00198','nombre':'PebbelsYBamBam-es','descripcion':'Pebbels y Bam Bam - Los Picapiedra','etiquetas':'Pebbels y Bam Bam Los Picapiedra muñeco caricatura bonito'},
  { 'codigo':'00199','nombre':'PebblesPicapiedra-es','descripcion':'pebbles Picapiedra','etiquetas':'pebbles Picapiedra muñeco caricatura'},
  { 'codigo':'00200','nombre':'PeppaPigenPijamas-es','descripcion':'Peppa Pig en pijamas','etiquetas':'Peppa Pig en pijamas cochino caricatura'},
  { 'codigo':'00201','nombre':'Perritos-es','descripcion':'Perritos','etiquetas':'Perritos perro chihuahua pastor alemán'},
  { 'codigo':'00202','nombre':'PerroPug-es','descripcion':'perro Pug','etiquetas':'perro pug'},
  { 'codigo':'00203','nombre':'PerroPugOjon-es','descripcion':'perro Pug ojón','etiquetas':'perro Pug ojón'},
  { 'codigo':'00204','nombre':'PinochoArticulado-es','descripcion':'Pinocho articulado','etiquetas':'Pinocho articulado caricatura'},
  { 'codigo':'00205','nombre':'PocoyoYNina-es','descripcion':'Pocoyó y Nina','etiquetas':'Pocoyó y Nina caricatura animado'},
  { 'codigo':'00206','nombre':'PrincipitoLunaZoRosa-es','descripcion':'El Principito, luna, zorro y rosa en frasco','etiquetas':'El Principito, luna, zorro y rosa en frasco libro'},
  { 'codigo':'00207','nombre':'PugRotSnaHus-es','descripcion':'Pug, Rottweiler, Schnauzer y Husky','etiquetas':'Pug, Rottweiler, Schnauzer y Husky perro'},
  { 'codigo':'00208','nombre':'PulpoLila-es','descripcion':'pulpo','etiquetas':'pulpo lila'},
  { 'codigo':'00209','nombre':'PVZCarnivora-es','descripcion':'planta carnívora - PVZ','etiquetas':'planta carnívora PVZ gamer videojuego'},
  { 'codigo':'00210','nombre':'PVZGirasol-es','descripcion':'girasol - PVZ','etiquetas':'girasol PVZ  gamer videojuego'},
  { 'codigo':'00211','nombre':'PVZombi-es','descripcion':'zombi - PVZ','etiquetas':'zombi PVZ gamer videojuego'},
  { 'codigo':'00212','nombre':'RanaReneBB30cm-es','descripcion':'rana René baby 30cm','etiquetas':'rana René baby 30cm película'},
  { 'codigo':'00213','nombre':'RanaTima-es','descripcion':'rana Tima','etiquetas':'rana Tima'},
  { 'codigo':'00214','nombre':'RatonIman-es','descripcion':'imán Ratón','etiquetas':'imán Ratón'},
  { 'codigo':'00215','nombre':'RenoHarry-es','descripcion':'reno Harry','etiquetas':'reno Harry navidad'},
  { 'codigo':'00216','nombre':'RenoNavideno-es','descripcion':'reno navideño','etiquetas':'reno navideño navidad'},
  { 'codigo':'00217','nombre':'RickSanchez-es','descripcion':'Rick Sánchez','etiquetas':'Rick Sánchez caricatura'},
  { 'codigo':'00218','nombre':'RosaAbierta-es','descripcion':'rosa abierta','etiquetas':'rosa abierta flor'},
  { 'codigo':'00219','nombre':'RosaCerrada-es','descripcion':'rosa cerrada','etiquetas':'rosa cerrada flor'},
  { 'codigo':'00220','nombre':'RosAmarilla-es','descripcion':'rosa amarilla','etiquetas':'rosa amarilla flor'},
  { 'codigo':'00221','nombre':'Rosas-es','descripcion':'rosa','etiquetas':'rosa flor'},
  { 'codigo':'00222','nombre':'SerpienteGde-es','descripcion':'serpiente grande','etiquetas':'serpiente grande'},
  { 'codigo':'00223','nombre':'Silvestre-es','descripcion':'Silvestre','etiquetas':'Silvestre caricatura'},
  { 'codigo':'00224','nombre':'SnorlaxPokemon46cm-es','descripcion':'Snorlax Pokémon 46cm','etiquetas':'Snorlax Pokémon 46cm'},
  { 'codigo':'00225','nombre':'SoldadoJuegoDelCalamar-es','descripcion':'soldado Juego del Calamar','etiquetas':'soldado Juego del Calamar serie'},
  { 'codigo':'00226','nombre':'SonajeroConejito-es','descripcion':'sonajero conejito','etiquetas':'sonajero conejito'},
  { 'codigo':'00227','nombre':'SonajeroJirafa-es','descripcion':'sonajero jirafa','etiquetas':'sonajero jirafa'},
  { 'codigo':'00228','nombre':'SonajeroMariquitaRochi-es','descripcion':'sonajero mariquita Rochi','etiquetas':'sonajero mariquita Rochi'},
  { 'codigo':'00229','nombre':'SonicKnuckles-es','descripcion':'Sonic y Knuckles','etiquetas':'Sonic y Knuckles'},
  { 'codigo':'00230','nombre':'SpidermanConYSinMascara-es','descripcion':'Hombre Araña cabeza con y sin máscara','etiquetas':'Hombre Araña cabeza con y sin máscara'},
  { 'codigo':'00231','nombre':'Tulipanes-es','descripcion':'tulipán plus','etiquetas':'tulipán plus flor'},
  { 'codigo':'00232','nombre':'UnicornioBetty-es','descripcion':'unicornio Betty','etiquetas':'unicornio Betty'},
  { 'codigo':'00233','nombre':'UnicornioMicro-es','descripcion':'unicornio mini','etiquetas':'unicornio mini'},
  { 'codigo':'00234','nombre':'UnicornioMini-es','descripcion':'unicornio','etiquetas':'unicornio'},
  { 'codigo':'00235','nombre':'UnicornioPegaso-es','descripcion':'unicornio pegaso','etiquetas':'unicornio pegaso'},
  { 'codigo':'00236','nombre':'VeranoSietePatrones-es','descripcion':'Edición verano','etiquetas':'Edición verano flamingo conejo vaca caballito de mar gato sirena muñeca doll'},
  { 'codigo':'00237','nombre':'WandaPadrinosMagicos-es','descripcion':'Wanda - Los Padrinos Mágicos','etiquetas':'Wanda - Los Padrinos Mágicos caricatura'},
  { 'codigo':'00238','nombre':'Winnie-es','descripcion':'Winnie Pooh','etiquetas':'Winnie Pooh libro caricatura mini'},
  { 'codigo':'00239','nombre':'Yoda-es','descripcion':'Yoda','etiquetas':'Yoda viejo película'},  
];